import type { Product } from "./order-service"

export const staplesProducts: Omit<Product, "id" | "createdAt" | "updatedAt">[] = [
  // Pulses & Lentils
  {
    name: "Chana Dal (1 kg)",
    sku: "PULSE-CHANA-1KG",
    description: "Premium quality chana dal, split chickpea lentils, rich in protein",
    price: 120.0, // INR
    cost: 95.0,
    stock: 150,
    lowStockThreshold: 30,
    category: "Pulses & Lentils",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 20.0, width: 15.0, height: 5.0 },
  },
  {
    name: "Toor Dal (1 kg)",
    sku: "PULSE-TOOR-1KG",
    description: "Fresh toor dal (pigeon pea), essential for daily cooking",
    price: 140.0,
    cost: 115.0,
    stock: 120,
    lowStockThreshold: 25,
    category: "Pulses & Lentils",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 20.0, width: 15.0, height: 5.0 },
  },
  {
    name: "Moong Dal (1 kg)",
    sku: "PULSE-MOONG-1KG",
    description: "Yellow moong dal, quick cooking and nutritious",
    price: 160.0,
    cost: 135.0,
    stock: 100,
    lowStockThreshold: 20,
    category: "Pulses & Lentils",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 20.0, width: 15.0, height: 5.0 },
  },

  // Rice & Grains
  {
    name: "Basmati Rice (5 kg)",
    sku: "RICE-BASMATI-5KG",
    description: "Premium long grain basmati rice, aromatic and fluffy",
    price: 450.0,
    cost: 380.0,
    stock: 80,
    lowStockThreshold: 15,
    category: "Rice & Grains",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 5.0,
    dimensions: { length: 40.0, width: 25.0, height: 8.0 },
  },
  {
    name: "Wheat Flour (5 kg)",
    sku: "FLOUR-WHEAT-5KG",
    description: "Fresh wheat flour (atta) for making rotis and bread",
    price: 280.0,
    cost: 240.0,
    stock: 90,
    lowStockThreshold: 20,
    category: "Rice & Grains",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 5.0,
    dimensions: { length: 35.0, width: 25.0, height: 8.0 },
  },
  {
    name: "Poha (1 kg)",
    sku: "GRAIN-POHA-1KG",
    description: "Flattened rice flakes, perfect for breakfast and snacks",
    price: 85.0,
    cost: 65.0,
    stock: 60,
    lowStockThreshold: 15,
    category: "Rice & Grains",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 25.0, width: 20.0, height: 5.0 },
  },

  // Cooking Oils
  {
    name: "Sunflower Oil (1 Liter)",
    sku: "OIL-SUNFLOWER-1L",
    description: "Pure sunflower cooking oil, heart healthy and light",
    price: 180.0,
    cost: 155.0,
    stock: 75,
    lowStockThreshold: 15,
    category: "Cooking Oils",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.9,
    dimensions: { length: 25.0, width: 8.0, height: 8.0 },
  },
  {
    name: "Mustard Oil (1 Liter)",
    sku: "OIL-MUSTARD-1L",
    description: "Pure mustard oil, traditional cooking oil with strong flavor",
    price: 220.0,
    cost: 190.0,
    stock: 50,
    lowStockThreshold: 12,
    category: "Cooking Oils",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.9,
    dimensions: { length: 25.0, width: 8.0, height: 8.0 },
  },

  // Spices & Condiments
  {
    name: "Turmeric Powder (100g)",
    sku: "SPICE-TURMERIC-100G",
    description: "Pure turmeric powder, essential spice for Indian cooking",
    price: 45.0,
    cost: 32.0,
    stock: 200,
    lowStockThreshold: 50,
    category: "Spices & Condiments",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.1,
    dimensions: { length: 12.0, width: 8.0, height: 3.0 },
  },
  {
    name: "Red Chili Powder (100g)",
    sku: "SPICE-CHILI-100G",
    description: "Hot red chili powder, adds heat and flavor to dishes",
    price: 55.0,
    cost: 40.0,
    stock: 180,
    lowStockThreshold: 45,
    category: "Spices & Condiments",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.1,
    dimensions: { length: 12.0, width: 8.0, height: 3.0 },
  },
  {
    name: "Garam Masala (50g)",
    sku: "SPICE-GARAM-50G",
    description: "Authentic garam masala blend, aromatic spice mix",
    price: 65.0,
    cost: 45.0,
    stock: 120,
    lowStockThreshold: 30,
    category: "Spices & Condiments",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.05,
    dimensions: { length: 10.0, width: 6.0, height: 3.0 },
  },

  // Tea & Beverages
  {
    name: "Tea Leaves (250g)",
    sku: "BEV-TEA-250G",
    description: "Premium Assam tea leaves, strong and flavorful",
    price: 95.0,
    cost: 75.0,
    stock: 90,
    lowStockThreshold: 20,
    category: "Tea & Beverages",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.25,
    dimensions: { length: 15.0, width: 10.0, height: 5.0 },
  },

  // Sugar & Sweeteners
  {
    name: "Sugar (1 kg)",
    sku: "SWEET-SUGAR-1KG",
    description: "Pure white sugar crystals for cooking and beverages",
    price: 50.0,
    cost: 42.0,
    stock: 150,
    lowStockThreshold: 30,
    category: "Sugar & Sweeteners",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 20.0, width: 15.0, height: 5.0 },
  },
  {
    name: "Jaggery (500g)",
    sku: "SWEET-JAGGERY-500G",
    description: "Pure jaggery (gur), natural sweetener rich in minerals",
    price: 70.0,
    cost: 55.0,
    stock: 80,
    lowStockThreshold: 18,
    category: "Sugar & Sweeteners",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 0.5,
    dimensions: { length: 15.0, width: 12.0, height: 4.0 },
  },

  // Salt & Seasonings
  {
    name: "Rock Salt (1 kg)",
    sku: "SEASON-SALT-1KG",
    description: "Pure rock salt, natural and unrefined",
    price: 35.0,
    cost: 25.0,
    stock: 100,
    lowStockThreshold: 25,
    category: "Salt & Seasonings",
    status: "active",
    images: ["/placeholder.svg?height=200&width=200"],
    weight: 1.0,
    dimensions: { length: 18.0, width: 12.0, height: 4.0 },
  },
]
